### ISSUE TITLE
Generation of OpenAPI document from a "metamodel"

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-open-api#244] opened 2020-01-24 14:56 UTC
For Quarkus there is work being investigated around generation of endpoints into bytecode during the build, but as the implementation relies on Jandex at present, any endpoints from bytecode wouldn't be present.

We want to extract the Jandex input to a fallback of some kind, and define a "metamodel" that runtimes can pass to the implementation to generate the OpenAPI definition from.

This would also help in solving #217.

**Comment by EricWittmann** [comment] 2020-01-25 22:15
Just to be clear - the task is to put an abstraction layer in between Jandex and the annotation scanner?  That way openapi can be generated from sources other than .class files?

For this use-case, how are the endpoints generated into bytecode?  Where are these endpoints defined?

**Comment by kenfinnigan** [comment] 2020-01-27 18:43
Yes. The project can still have a way to use a Jandex parser to create the metamodel, as it does today, but there's an intermediary step so we can decouple them.

Quarkus wants to introduce the build-time generation of endpoints, but they can't be re-indexed by Jandex to then feed into the OpenAPI process

**Comment by EricWittmann** [comment] 2020-01-27 19:17
Yeah - but build time generation of endpoints based on what?

**Comment by kenfinnigan** [comment] 2020-01-27 19:26
Sorry, generating endpoints at boot time based on other annotations present within the code.

An example would be creating a new Resource with CRUD endpoints on it based on an `Entity` having `@CRUD` present on it. That's just a poor example, but the idea is creating endpoints based on annotations in the code

**Comment by MikeEdgar** [comment] 2020-01-28 10:27
Is the work to define an programming interface for the meta-model part of this issue or is that being done in Quarkus? Are the generated endpoints not ultimately being saved as class files?

**Comment by kenfinnigan** [comment] 2020-01-28 14:45
The metamodel would need to be developed here, but then "created" by Quarkus to feed into the OpenAPI generation process.

The generated endpoints are saved as class files, I believe, but it occurs at a point in the process that would mean it's expensive to re-index all the code to create an up to date Jandex index for processing

**Comment by MikeEdgar** [comment] 2020-01-28 15:46
If the newly generated classes will be on the class path or in known location(s) at the point SRye OpenAPI is invoked, it might be worthwhile to look at going with an implementation of `org.jboss.jandex.IndexView` that lazily indexes the list of classes that were generated. That `IndexView` could be added to the `org.jboss.jandex.CompositeIndex` already being passed and things just work without too much (if any) other change to the scanner.

**Comment by kenfinnigan** [comment] 2020-01-28 15:53
@FroMage can you recall if the generated classes would be on the classpath and this approach could work?

I can't recall all the details of how the endpoint generation was going to work

**Comment by kenfinnigan** [comment] 2020-01-31 15:42
Another reason for a separate metamodel could be aligning with CDI in the sense that CDI Extensions, granted outside the realm of Quarkus, can modify JAX-RS Resources if they're CDI Beans, so it would also be good to be able to create an OpenAPI model of post CDI Extension changes, which would also be post Jandex indexing.

**Comment by MikeEdgar** [comment] 2020-02-03 01:07
There are a couple of scenarios where we generate internal Jandex indexes mainly to support known (and very common) JDK types. If we take the route of implementing a custom `IndexView` then the additional classes generated/modified after the primary Jandex indexing phase in Quarkus could still be indexed on the fly by the OpenAPI scanner. As mentioned earlier, the classes would either need to be on the class path or in an accessible location.

Jandex is very deeply ingrained in the annotation scanning process. If we know the answer regarding whether the classes representing generated/augmented endpoints will be available, I can put together a PR with an `IndexView` to support yet-to-be indexed classes.

**Comment by EricWittmann** [comment] 2020-02-03 12:03
Certainly if the classes can be indexed that would be ideal - perhaps one of the dynamic class generating projects can produce something that can be indexed by jandex?  Byteman or asm?

That said, a meta-model is certainly possible to implement, just requires quite a lot of reworking.

**Comment by kenfinnigan** [comment] 2020-02-03 18:50
@FroMage are you able to comment as to whether any Quarkus generated bytecode that adds new endpoints would be on the classpath at the point the OpenAPI document is created?

From recollection, the document is created at build time, but I suspect the generated classes wouldn't be on the build time classpath. But I could be wrong

**Comment by EricWittmann** [comment] 2020-02-03 18:53
This is a really good point, and something I just learned recently - currently in Quarkus the OpenAPI doc is created at build time, not at runtime.  These classes are not generated at build time?

**Comment by kenfinnigan** [comment] 2020-02-03 18:55
The endpoint classes will be generated during the build process, but I'm not certain they'd be added to the build time classpath in the same build process.

**Comment by MikeEdgar** [comment] 2020-02-03 20:43
If they're on the class path, that would be good. But if they are not, are they available as class files that are accessible?

**Comment by phillip-kruger** [comment] 2020-05-30 17:02
Hi @kenfinnigan . #217 is solved now (by adding support for Spring annotations). Do we still need this ? And if we do, if I understand correctly, at the moment we generate the schema document on build in Quarkus and then pass that document to the runtime, but this would allow us to pass the model to the runtime, also giving other build items the chance to update the model ? 

We actually already have a model, so we should already be able to do this (I think). We just need to make sure that model serialize properly.

Let me know .

**Comment by kenfinnigan** [comment] 2020-05-30 21:03
I don't know if we want to pass the model into runtime, but still generate it at build time.

This is needed so that Quarkus can add endpoints that are generated at build time into the API schema model. The issue at present is the model is Jandex based. For adding pieces at build time, it would be easier if it was an actual metamodel.

At least that's my recollection. @FroMage might have other thoughts too

**Comment by phillip-kruger** [comment] 2020-05-31 07:49
We can make the final `org.eclipse.microprofile.openapi.models.OpenAPI` (that is a clean model, no Janex - even though we build it from Jandex) available as a build item in Quarkus via SPI so that other extensions can get to it ?

You can then add parts to that document ? @FroMage is this what you need ? 

I think we can close this issue here and if this is what is needed we can open a issue in Quarkus as this is where the work will be. w.d.y.t ? @kenfinnigan ?

**Comment by kenfinnigan** [comment] 2020-06-01 12:16
Let's wait for @FroMage to comment before we close this

**Comment by FroMage** [comment] 2020-06-02 12:17
If I understand correctly, you want to allow us to register our endpoints using the existing `OpenAPI` API?

Now, given that we generate some JAX-RS endpoints (@gytis does that), and those are not indexed, it's possible that calling this `OpenAPI` API works out fine, but it's also possible that we'll have to duplicate all the logic of mapping JAX-RS annotations to `OpenAPI` in order to call it, no?

**Comment by phillip-kruger** [comment] 2020-06-02 12:22
I might be slow to understand the requirement, so maybe rather then me describing what we can do (the solution) maybe you can describe the problem ? Do you have other (JAX-RS) annotations in source that is not in the Jandex index ?

**Comment by FroMage** [comment] 2020-06-02 12:28
At build time we generate some JAX-RS endpoints. Those are not indexed, because they're generated, and we still want to enlist them to openapi.

Perhaps it's as easy as making a build item listing those generated endpoints so that the quarkus extension for openapi would index them and combine the index with the normal index before scanning.

**Comment by phillip-kruger** [comment] 2020-07-10 19:06
@FroMage - this seems to work in Quarkus 1.6? The generated endpoints show up in OpenAPI as far as I can see.

**Comment by phillip-kruger** [comment] 2020-07-15 10:21
Confirmed fixed by Gytis Trikleris. Closing

**Closed by phillip-kruger** 2020-07-15 10:21 UTC
Labels: enhancement
