### ISSUE TITLE
Order of properties in class not maintained

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-open-api#314] opened 2020-04-29 20:14 UTC
Especially with a code first approach I would assume the order of the properties as defined in a class will be maintained in the generated schema.

But instead the properties in the generated schema are alphabetically.

I tried configuring the order strategy in the JsonbConfig of my Quarkus app but Jsonb seems not to have an option to keep the order of the properties in the class, unlike e.g. Jackson supports this.

I also tried switching to quarkus-resteasy-jackson (instead of jsonb) and the actual JSON output is ordered as in the class, but the generated openapi schema the properties are still ordered alphabetically.

**Comment by phillip-kruger** [comment] 2020-04-29 20:19
Will this help: https://github.com/eclipse/microprofile-open-api/issues/359 ?

**Comment by marceloverdijk** [comment] 2020-04-29 20:33
Yes exactly that.
I read your comment about the `@Order` annotation and keeping in sync.

You mean with this keeping the order in the generated openapi doc the same as in actual json output?
So this would be an annotation used by both Jsonb and MP openapi?

**Comment by MikeEdgar** [comment] 2020-04-29 20:38
It would be OpenAPI only. Please try JsonbPropertyOrder on your POJO.

**Comment by MikeEdgar** [comment] 2020-04-29 20:51
I say that mainly because `@Order` won't be available for a while yet.

**Comment by marceloverdijk** [comment] 2020-04-30 06:11
Yes, `@JsonbPropertyOrder` is picked up both in the generated openapi schema and the actual json output of the service.

It's unfortunate Jsonb doesn't support a natural sorting option that can be set globally.
Anyway it does the trick for now. Thx.

**Comment by marceloverdijk** [comment] 2020-04-30 06:26
PS: Created this [issue](https://github.com/eclipse-ee4j/jsonb-api/issues/236) in the Jsonb spec project to introduce a global `NATURAL` support option. Probably a long shot...

**Comment by MikeEdgar** [comment] 2020-05-01 12:32
Thanks @marceloverdijk. I am going to go ahead and close this as the root cause is the same as #87. Please feel free to re-open if you feel differently, etc.

**Closed by MikeEdgar** 2020-05-01 12:32 UTC
