### ISSUE TITLE
Wrong java.time.Instant properties schema

### ISSUE THREAD

**Issue by hrensgory** [smallrye/smallrye-open-api#812] opened 2021-06-01 16:58 UTC
Hi,

I have a problem with java.time.Instant properties representation in OpenAPI, generated by smallrye-open-api

Environment: Quarkus 1.13.6, Kotlin 1.4.32

Data class:

@Schema(description = "Quark")
    data class Quark (
        val name: String? = null,
        val description: String? = null,
        @Schema(description = "created date", type = SchemaType.STRING, format = "date-time")
        val createdDate: Instant
    )
    
JSON output from service looks ok: 

{

    "name": "Charm",
    "description": "The charm quark, charmed quark or c quark (from its symbol, c) is the third most massive of all quarks, a type of elementary particle.",
    "createdDate": "2021-06-01T16:52:52.837152100Z"

}    
    
Expected schema is something like this:

    Quark:
      description: Quark
      type: object
      properties:
        createdDate:
          type: string
          format: "date-time"
        description:
          type: string
        name:
          type: string
          
Real schema, generated at http://localhost:8080/openapi is much more verbose:

    Instant:
      type: object
      properties:
        nanos:
          format: int32
          type: integer
        seconds:
          format: int64
          type: integer
        epochSecond:
          format: int64
          type: integer
        nano:
          format: int32
          type: integer
    Quark:
      description: Quark
      type: object
      properties:
        createdDate:
          $ref: '#/components/schemas/Instant'
        description:
          type: string
        name:
          type: string
                  
please suggest how to get rid of unnecessary (and wrong ) "Instant" object.   
Minimal reproduced attached - [code-with-quarkus.zip](https://github.com/smallrye/smallrye-open-api/files/6577856/code-with-quarkus.zip)

Thanks in advance.

**Comment by MikeEdgar** [comment] 2021-06-01 17:02
@phillip-kruger - this is fixed on `2.0.x` but not yet released.

**Comment by hrensgory** [comment] 2021-06-01 17:57
@MikeEdgar - thanks for the answer!

BTW, I found the workaround:

@field: Schema(
  description = "created date", 
  type = SchemaType.STRING, 
  implementation = String::class,
  format = "date-time"
)
val createdDate

works fine for me.

**Comment by MikeEdgar** [comment] 2021-06-01 22:38
@hrensgory, I am marking this a duplicate of #769, fixed by #771 (yet to be released). @phillip-kruger, it might make sense to do another release from `2.0.x` for the downstream projects that are still supporting MP OpenAPI 1.1. wdyt?

**Comment by phillip-kruger** [comment] 2021-06-02 07:18
We can do that. I'll do a release now. @hrensgory Quarkus 2 is nearly out, and the issue is fixed there. Try with CR2 to confirm.

**Comment by phillip-kruger** [comment] 2021-06-02 07:18
Closing here (to do the release)

**Closed by phillip-kruger** 2021-06-02 07:18 UTC
Labels: bug, duplicate

**Comment by hrensgory** [comment] 2021-06-02 08:10
> We can do that. I'll do a release now. @hrensgory Quarkus 2 is nearly out, and the issue is fixed there. Try with CR2 to confirm.

CR2 works like a charm.  Thank you, @phillip-kruger

**Comment by phillip-kruger** [comment] 2021-06-02 08:12
Ok great, are you ok to wait for Quarkus 2, or should we backport ?

**Comment by hrensgory** [comment] 2021-06-02 08:50
We're ok to wait. Thank you!
