### ISSUE TITLE
[inquiry] Failing Tests While Buiding 2.1.0-RC1 locally

### ISSUE THREAD

**Issue by emecas** [smallrye/smallrye-open-api#605] opened 2020-12-16 19:57 UTC
I've been trying to build locally 2.1.0-RC1, but I'm facing issues with 2 or 4 tests failing (depending of JDK's version) during `SmallRye: MicroProfile OpenAPI TCK` maven goal, any advise?  

#### JDK8

Class | Method | Start | Time (ms)
-- | -- | -- | --
Surefire suite
Surefire test — failed (configuration methods)
io.smallrye.openapi.tck.TestApplication | arquillianAfterSuite | 1608145497440 | 56
org.eclipse.microprofile.openapi.tck.ModelConstructionTest | arquillianBeforeTest | 1608145408944 | 1
org.eclipse.microprofile.openapi.tck.OASFactoryErrorTest | arquillianBeforeTest | 1608145497302 | 0
Surefire test — failed
org.eclipse.microprofile.openapi.tck.OASFactoryErrorTest | customAbstractClassTest | 1608145495888 | 1412

#### JDK11

Class | Method | Start | Time (ms)
-- | -- | -- | --
Surefire suite
Surefire test — failed (configuration methods)
io.smallrye.openapi.tck.TestApplication | arquillianAfterSuite | 1608136493988 | 21
org.eclipse.microprofile.openapi.tck.ModelConstructionTest | arquillianBeforeTest | 1608136408466 | 1

Also,  graphviz  installation is part of the checks setup, wonder what is its  utility during the build ? where is it being used ?  

I noticed that microprofile-open-api GitHub checks are failing since [Dec 07 1cf3a1d74](https://github.com/eclipse/microprofile-open-api/commit/1cf3a1d74205055b99ca995c70d68dab739bb6d5),  but  I'm not 100% sure that could be the root cause for the failing tests, since the checks here have passed.

Thanks

**Comment by radcortez** [comment] 2020-12-17 12:07
Indeed, it seems there is some issue with the build using the RC1 tag. I've tried it locally and run into the same problems, but master works fine. @phillip-kruger @MikeEdgar can anyone of you confirm?

**Comment by MikeEdgar** [comment] 2020-12-17 13:02
@radcortez , @emecas - this started recently and I have not yet had time to dig in to understand the cause of it. I assumed it was something with my local configuration (I believe Phillip had the same problem) since the Github actions build and run the TCK without any issue. The build failures on `master` were unrelated to this and the current errors is only a Sonar check that is failing, not the build/tests.

**Comment by radcortez** [comment] 2020-12-17 21:27
When I rewrote the TCK, I remember I was having issues with Jetty 9.4.x and had to downgrade to 9.3.x. When I downgrade Jetty in the RC1 tag it works fine.

I wonder why it works on GH Actions...

**Comment by MikeEdgar** [comment] 2020-12-17 22:08
Confirmed that using 9.3.x works for me as well. Perhaps because org.jboss.arquillian.container:arquillian-jetty-embedded-9 is expecting 9.3? That does not explain the GH Action difference of course.

**Comment by emecas** [comment] 2020-12-18 04:21
Thanks @radcortez  @MikeEdgar ,  I added my observations in #607,  but as you have mentioned,  it does not explain why GitHub checks are passing.

 > Also, graphviz installation is part of the checks setup, wonder what is its utility during the build ? where is it being used ?

I'd like reiterate on this point.

**Comment by MikeEdgar** [comment] 2020-12-18 11:34
@emecas - up until just recently (commit 2d65f320a68f093c7cb4eee9adfb7d65b336e731), the JavaDocs were being generated with UML diagrams and I believe that was necessary for the process. Since that was removed, we can likely remove the installation of graphviz as well.

**Comment by radcortez** [comment] 2020-12-18 11:46
> Confirmed that using 9.3.x works for me as well. Perhaps because org.jboss.arquillian.container:arquillian-jetty-embedded-9 is expecting 9.3? That does not explain the GH Action difference of course.

Yes, it was aligned with Arquillian version and 9.4.x doesn't seem to work. I was wondering if this was a MacOS issue and I added a Windows builder to my fork, and that also works. This is puzzling me...

**Comment by MikeEdgar** [comment] 2020-12-18 11:49
I'm running on Linux with the same issue also, no more generally *nix seems impacted.

Pure speculation, but I wonder if it is somehow related to timing and port 8080 availability between tests. The original TCK framework that ran via JUnit also had a problem with port conflicts at one point, I believe.

**Comment by radcortez** [comment] 2020-12-18 11:57
When I rewrote the TCK I remember having a quick look and for some reason between version 9.3.x and 9.4.x, Arquillian was redeploying the application between tests which internally caused some issues with the `WebContextClassLoader`. Maybe the issue is related with the classpath scanning ordering and explain why it works in some environments and fail in others.

**Comment by MikeEdgar** [comment] 2020-12-19 14:33
> In line with your observations on #607, 11.0.9.1 (AdoptOpenJDK) also fails for me whereas 11.0.9 succeeds.

I don't think this is an issue (for us). It seems Jetty is unable to parse the `.1` and considers `11.0.9.1` to be an invalid Java version.

**Comment by emecas** [comment] 2020-12-19 17:46
> 
> 
> > In line with your observations on #607, 11.0.9.1 (AdoptOpenJDK) also fails for me whereas 11.0.9 succeeds.
> 
> I don't think this is an issue (for us). It seems Jetty is unable to parse the `.1` and considers `11.0.9.1` to be an invalid Java version.

@MikeEdgar  good point,  _It seems this is all about a dot!!_ :) 

- the `.`  after  the minor version, since for this case mvn is not even getting to the point to show the build summary
- the  `_`  in `Java version: 1.8.0_112` is failing specific tests, but it shows a mvn build summary
- the `-`  in `Java version: 1.8.0-272` is working
- and `nothing`  like `Java version: 11.0.1`  or `11.09` is working

I have tested as well with 3 more JDK versions, all 3 build passed :  

- `Java version: 13`
- `Java version: 14.0.2`
- `Java version: 15`

CC: @radcortez

**Comment by MikeEdgar** [comment] 2020-12-20 16:16
@emecas - interesting find. It looks like the Java version parsing has been updated in more recent versions of Jetty, but the Arquillian wrapper does not yet support those versions. 

Since #607 has been incorporated and we seem to have pinpointed the version number issue as a third-party problem, is there anything else needed to resolve this ticket?

**Comment by emecas** [comment] 2020-12-21 02:06
> 
> @emecas - interesting find. It looks like the Java version parsing has been updated in more recent versions of Jetty, but the Arquillian wrapper does not yet support those versions.
> 

Do you know the fix for this in Jetty project?  This one was what I found: 

https://github.com/eclipse/jetty.project/issues/5793

That is referencing this:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=475546

I tried to reproduce and isolate better error messages in order to get more concrete searching terms,  and  potentially find in the related bug a better understanding, but I did not succeed. 

These are some of the error mesges I can see , but at the same time these does not have any thing in common to the mentioned bug for Jetty project:

```
[2020-12-20 19:02:00] [WARNING] Unable to reach node goal: started
[2020-12-20 19:02:00] [WARNING] Unable to reach node goal: started
[2020-12-20 19:02:00] [WARNING] Unable to reach node goal: undeployed
[2020-12-20 19:02:01] [INFO   ] Stopping Jetty Embedded Server [id:1262110193]
[2020-12-20 19:02:01] [INFO   ] Stopped ServerConnector@41925502{HTTP/1.1,[http/1.1]}{localhost:8080}
[ERROR] Tests run: 244, Failures: 214, Errors: 0, Skipped: 0, Time elapsed: 35.256 s <<< FAILURE! - in TestSuite
[ERROR] openApi(io.smallrye.openapi.tck.TestApplication)  Time elapsed: 0.67 s  <<< FAILURE!
java.lang.AssertionError: expected [200] but found [404]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:652)
        at org.testng.Assert.assertEquals(Assert.java:662)
        at io.smallrye.openapi.tck.TestApplication.openApi(TestApplication.java:60)
```

```
[ERROR] rest(io.smallrye.openapi.tck.TestApplication)  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: expected [200] but found [404]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:652)
        at org.testng.Assert.assertEquals(Assert.java:662)
        at io.smallrye.openapi.tck.TestApplication.rest(TestApplication.java:50)
```
```

[ERROR] testFilterAPIResponse(org.eclipse.microprofile.openapi.tck.FilterTest)  Time elapsed: 0.947 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <404>.

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:674)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:126)
        at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:134)
        at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
        at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1267)
```

> Since #607 has been incorporated and we seem to have pinpointed the version number issue as a third-party problem, is there anything else needed to resolve this ticket?

I don't think so, since root cause is clear, I was just waiting for your reply and maybe replies from @radcortez  and/or  anybody else who could be interested. 

On the other hand, let me ask a couple question to get a better context, I know the subject is an external thing to this project, but I'm wondering: 

1) do we need an open issue to track Arquillian wrapper upgrading to a newer Jetty version which includes that fix for the identified problem here?  I found [this](http://arquillian.org/modules/arquillian-jetty-embedded-9-container-adapter/) , but it seems this is not active since 2016/2017.

2) what would be an alternative to jetty /  Arquillian wrapper into this context?

**Comment by radcortez** [comment] 2021-01-04 12:08
> 1. do we need an open issue to track Arquillian wrapper upgrading to a newer Jetty version which includes that fix for the identified problem here?  I found [this](http://arquillian.org/modules/arquillian-jetty-embedded-9-container-adapter/) , but it seems this is not active since 2016/2017.

We probably need to go there and update it.

> 2. what would be an alternative to jetty /  Arquillian wrapper into this context?

We could probably use Undertow instead of Jetty.

**Comment by phillip-kruger** [comment] 2021-02-22 03:21
Can we close this ? @emecas @radcortez

**Comment by radcortez** [comment] 2021-02-22 18:56
Fine for me.

**Comment by phillip-kruger** [comment] 2021-02-22 19:00
Closing. Please reopen if you believe this is still an issue. Thanks :)

**Closed by phillip-kruger** 2021-02-22 19:00 UTC
