### ISSUE TITLE
Parameterized response types not generated correctly

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-open-api#320] opened 2020-05-04 14:50 UTC
I'm experimenting a bit with the SmallRye impl in a Quarkus implementation and I wonder if there are some (documented) recommendations about return types. E.g. RESTEasy Response instance vs custom model classes.

For now I used the latter like:
```
public ContinentResource getContinent(..);
public PageResource<ContinentResource> getContinents(..)
```

This seemed ok, but when having another api endpoint class it seems the generated openapi schema for the generic PageResource give some problems.
E.g. I added:

```
public CountryResource getCountry(..)
public PageResource<CountryResource> getCountries(..)
```

Now the schema being generated contains:

![image](https://user-images.githubusercontent.com/197004/80978681-abc5f480-8e26-11ea-83cc-22bfb94fce51.png)

Besides the generated schema looks awkward, it is actually also **incorrect**.
All 3 generated page schema's (`Page`, `Page1`, `Page2`) look like:

![image](https://user-images.githubusercontent.com/197004/80978730-baaca700-8e26-11ea-9b66-a183785e080e.png)

So in all page definitions in contains an `elements` array of `Continent`.
For `getCountries` it should be an array of `Country`.

Probably I can solve it by introducing dedicated `ContinentPageResource` and `CountryPageResource` classes instead of using a generic `PageResource<T>`.

That's why I'm wondering about recommendations / limitations as the generated schema listens narrowly to how return classes are defined.

I created a sample Quarkus project which showcases this issue:

https://github.com/marceloverdijk/mp-openapi-schema-issue

**Comment by EricWittmann** [comment] 2020-05-04 16:22
Thanks for the report and the sample project!

**Comment by marceloverdijk** [comment] 2020-05-04 18:48
I tried some alternative this evening with:

```
public interface PageResource<T> {
    List<T> getElements();
    long getTotalElements();
    long getTotalPages();
    boolean isHasNextPage();
    boolean isHasPreviousPage();
}

@JsonbPropertyOrder({"elements", "totalElements", "totalPages", "hasNextPage", "hasPreviousPage" })
public abstract class BasePageResource<T> implements PageResource<T> {

    @Schema(name = "elements", description = "The elements of the page.", required = true)
    @JsonbProperty("elements")
    private List<T> elements;

    @Schema(name = "total-elements", description = "The total number of elements.", required = true)
    @JsonbProperty("total-elements")
    private long totalElements;

    @Schema(name = "total-pages", description = "The total number of pages.", required = true)
    @JsonbProperty("total-pages")
    private long totalPages;

    @Schema(name = "has-next-page", description = "Whether there is a next page.", required = true)
    @JsonbProperty("has-next-page")
    private boolean hasNextPage;

    @Schema(name = "has-previous-page",
            description = "Whether there is a previous page.",
            required = true)
    @JsonbProperty("has-previous-page")
    private boolean hasPreviousPage;

    public BasePageResource(List<T> elements, long totalElements, long totalPages, boolean hasNextPage, boolean hasPreviousPage) {
        this.elements = elements;
        this.totalElements = totalElements;
        this.totalPages = totalPages;
        this.hasNextPage = hasNextPage;
        this.hasPreviousPage = hasPreviousPage;
    }

    // getters omitted from this example
}

@Schema(name = "Country page", description = "Represents a country page.")
public class CountryPageResource extends BasePageResource<CountryResource> {

    public CountryPageResource(List<CountryResource> elements, long totalElements, long totalPages, boolean hasNextPage, boolean hasPreviousPage) {
        super(elements, totalElements, totalPages, hasNextPage, hasPreviousPage);
    }
}

@Path("/countries")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Tag(name = "country")
public class CountryApi {

    @GET
    @Operation(
            summary = "Retrieve a page of countries",
            description = "Retrieve a page of countries using the provided filtering, pagination and sorting parameters.")
    public CountryPageResource getCountryPage(..) {
      ..
    }
}
```

Note that the interface and abstract class do not have any `@Schema` annotations.

The generated schema is better this way but still contains an unexpected object (which is also wrong).

![image](https://user-images.githubusercontent.com/197004/81001463-1176a880-8e48-11ea-8fec-965a837cb0ba.png)

I did not expect the `ListObject` object in the schema and the `CountryPage`'s `element` is of type `Continent` but should be `Country`.
So I think parameterized types in general have an issue unfortunately.

**Comment by marceloverdijk** [comment] 2020-05-04 18:59
Went even further by removing the abstract `BasePageResource` class, so having only the `PageResource` interface and 2 implementing classes: `ContinentPageResource` and `CountryPageResource`. It means quite some duplicate code though :-(

The generated schema is now **correct**. But still contains some kind of intermediate `ListObject` (but now 2):

![image](https://user-images.githubusercontent.com/197004/81002748-12103e80-8e4a-11ea-83b3-8b637ad91a92.png)

**Comment by MikeEdgar** [comment] 2020-05-04 20:51
When I scan the sample application from the SmallRye library directly (as a unit test) it produces a much more sane output. The components/schemas section contains Country, Continent, Page1 (for Continent), Page2 (for Country), and a superfluous Page that is not referenced in `paths` anywhere. 

The difference between what we are seeing may have to do with additional information being in the Jandex index during the Quarkus scan. This is a complete guess, but have you tried building the project with Maven instead of Gradle? I don't have a reason why that would make a difference, but it's just another variable.

Example of the page type:
```json
"Page1" : {
        "description" : "Represents a page.",
        "required" : [ "elements", "total-elements", "total-pages", "has-next-page", "has-previous-page" ],
        "type" : "object",
        "properties" : {
          "elements" : {
            "description" : "The elements of the page.",
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Continent"
            }
          },
          "total-elements" : {
            "format" : "int64",
            "description" : "The total number of elements.",
            "type" : "integer"
          },
          "total-pages" : {
            "format" : "int64",
            "description" : "The total number of pages.",
            "type" : "integer"
          },
          "has-next-page" : {
            "description" : "Whether there is a next page.",
            "type" : "boolean"
          },
          "has-previous-page" : {
            "description" : "Whether there is a previous page.",
            "type" : "boolean"
          }
        }
      }
```

**Comment by MikeEdgar** [comment] 2020-07-15 09:06
I am hoping this is also resolved with #393 , but there does seem to be some Quarkus-specific issue going on here.

**Comment by MikeEdgar** [comment] 2020-08-01 01:30
@marceloverdijk - please confirm this is working as you expect in the current version of Quarkus. It looks much better to me.

**Comment by marceloverdijk** [comment] 2020-08-03 06:04
@MikeEdgar I'm back from holidays so will give it a try this week and will let you know.

**Comment by marceloverdijk** [comment] 2020-08-05 05:55
Hi @MikeEdgar, it looks better now, the references are correct now.

But it still has some intermediate `List*Resource` objects (`ListContinentResource` and `ListContinentResource`) in the schema unfortunately.
These also seem not be used, so I don't understand why they are generated as they clutter the schema.

![image](https://user-images.githubusercontent.com/197004/89376647-8d56ea00-d6f0-11ea-96cd-9b769dd9d633.png)

Note I updated the sample project.

**Comment by MikeEdgar** [comment] 2020-08-18 00:24
@marceloverdijk - it looks like there is something wrong with the UI. If you look at the raw JSON/YAML OpenAPI output, everything is used. The result pages use the `Continent page` type, which includes a `ListContinentResource`, which is a list of `Continents`. Overall the output looks accurate based on my understanding of the API.

Response reference the page:
```json
"responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Continent page"
                }
              }
            }
          }
        }

```
The three schemas for continents:
```json
      "Continent": {
        "description": "Represents a continent.",
        "required": [
          "id",
          "code",
          "name",
          "demonym"
        ],
        "type": "object",
        "properties": {
          "id": {
            "description": "The id of the continent.",
            "type": "string"
          },
          "code": {
            "description": "The code of the continent.",
            "type": "string"
          },
          "name": {
            "description": "The name of the continent.",
            "type": "string"
          },
          "demonym": {
            "description": "The demonym of the continent.",
            "type": "string"
          }
        }
      },
      "Continent page": {
        "description": "Represents a continent page.",
        "required": [
          "elements",
          "total-elements",
          "total-pages",
          "has-next-page",
          "has-previous-page"
        ],
        "type": "object",
        "properties": {
          "elements": {
            "allOf": [
              {
                "$ref": "#/components/schemas/ListContinentResource"
              },
              {
                "description": "The elements of the page."
              }
            ]
          },
          "total-elements": {
            "format": "int64",
            "description": "The total number of elements.",
            "type": "integer"
          },
          "total-pages": {
            "format": "int64",
            "description": "The total number of pages.",
            "type": "integer"
          },
          "has-next-page": {
            "description": "Whether there is a next page.",
            "type": "boolean"
          },
          "has-previous-page": {
            "description": "Whether there is a previous page.",
            "type": "boolean"
          }
        }
      },
      "ListContinentResource": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Continent"
        }
      }
```

**Comment by MikeEdgar** [comment] 2020-08-20 11:56
@marceloverdijk - please let us know if this issue needs to stay open or if you agree it's been resolved. Thanks

**Comment by marceloverdijk** [comment] 2020-08-20 12:01
I will have another look soon.
If you prefer we can close this one and I will re-open it later if necessary?

**Comment by MikeEdgar** [comment] 2020-08-20 12:02
I'm fine with keeping it open until it's confirmed to be correct.

**Comment by MikeEdgar** [comment] 2020-10-05 21:43
@marceloverdijk - I'm going to go ahead and close this issue, but please do not hesitate to re-open if you believe this is not yet resolved. Thanks

**Closed by MikeEdgar** 2020-10-05 21:43 UTC
Labels: bug
