### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space when OpenAPI is enabled and enums are used in a JAX-RS endpoint

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-open-api#185] opened 2019-10-02 18:42 UTC
As reported in https://github.com/quarkusio/quarkus/issues/4329, an OOME is thrown when the quarkus-smallrye-openapi extension is used and a JAX-RS endpoint has an enum as a query parameter. It works if smallrye-openapi 1.1.3 is used

**Comment by gsmet** [comment] 2019-10-03 07:30
@EricWittmann fwiw, we had reports from 2 different users on this just after our release. 

Do you think we could get a fix for our next release (probably next Wednesday)? If not I’ll downgrade to the previous version, looks like this one was introduced in the very last release. 

Thanks!

**Comment by MikeEdgar** [comment] 2019-10-03 10:27
@gsmet, I don't believe this to be specific to the most recent release. The cause seems more related to an excessive amount of scanning that occurs due to JDK classes being included in the Jandex index. A temporary work-around would be to exclude those classes from the OpenAPI scan:
```
mp.openapi.scan.exclude.packages=java.lang
```

I'd like to have that configuration be included in this library. The assumption is that ```java.lang``` will never be included in the scan, but it will need to be made explicit. I'm looking to have the fix finished and pushed shortly.

**Comment by EricWittmann** [comment] 2019-10-03 11:10
@MikeEdgar Have you reproduced this locally and therefore had a chance to analyze it?  I dont' see enough information in https://github.com/quarkusio/quarkus/issues/4329 to reach that "java.lang" conclusion.  To be clear - I'm not doubting your assessment, I'm just interested in whether you have a more interesting stack trace to report than the one in https://github.com/quarkusio/quarkus/issues/4329

**Comment by MikeEdgar** [comment] 2019-10-03 11:35
@EricWittmann - I was able to reproduce it locally, and with a slightly different stack trace:
```
Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.ArrayList.iterator(ArrayList.java:976)
        at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:189)
        at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:101)
        at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:190)
        at io.smallrye.openapi.runtime.scanner.FilteredIndexView.getClassByName(FilteredIndexView.java:108)
        at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:190)
        at io.smallrye.openapi.runtime.scanner.dataobject.AugmentedIndexView.getClassByName(AugmentedIndexView.java:63)
        at io.smallrye.openapi.runtime.util.TypeUtil.isA(TypeUtil.java:170)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.isA(TypeProcessor.java:280)
        at io.smallrye.openapi.runtime.scanner.dataobject.TypeProcessor.processType(TypeProcessor.java:136)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.readUnannotatedField(AnnotationTargetProcessor.java:184)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:134)
        at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:96)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:265)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:232)
        at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:168)
        at io.smallrye.openapi.runtime.util.SchemaFactory.introspectClassToSchema(SchemaFactory.java:267)
        at io.smallrye.openapi.runtime.util.SchemaFactory.typeToSchema(SchemaFactory.java:233)
        at io.smallrye.openapi.runtime.scanner.ParameterProcessor.getParameters(ParameterProcessor.java:540)
        at io.smallrye.openapi.runtime.scanner.ParameterProcessor.process(ParameterProcessor.java:400)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:582)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:435)
        at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner$$Lambda$504/0x0000000840338c40.accept(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
```
I used the Quarkus ```getting-started``` project along with this resource:
```java
@Path("/hello")
public class GreetingResource {

	public enum TestEnum {
		VAL1, VAL2, VAL3;
	}

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Operation(operationId = "hello")
    public String hello(@QueryParam("val") TestEnum value) {
        return "hello";
    }
}
```
Even being less heavy handed and excluding only ```java.lang.Object``` resolves this and significantly speeds up the scanning. Without being more familiar with how the index is originally built, it does appear from that trace that there are multiple levels of indexes. I have not looked at Jandex to understand the memory impacts of that.

Additionally, we are not supporting enums in parameters or responses properly - they both end up being simple objects. Fixing that part of the scanning by properly generating string schemas with the list of enum values does fix the immediate issue, but I think stopping the hierarchy scan when a parent class is ```java.lang.Object``` is the way to go to prevent this more generally.

**Comment by EricWittmann** [comment] 2019-10-03 12:09
Yes this is probably similar to:  https://github.com/smallrye/smallrye-open-api/pull/169

The fact that all of the core java classes live in the index is probably more broadly problematic for us.  I think my fix in the PR above is probably just addressing one specific case.  I suspect we should exclude some standard java packages from the index.

We should probably also open a separate issue if the enums in parameters/responses aren't being properly supported.  I had that same issue in a codegen library in Apicurio, so am not surprised I missed it originally here too. :)

**Comment by MikeEdgar** [comment] 2019-10-03 12:16
I've been running this through the debugger, and without any changes, the call to ```TypeResolver.getAllFields``` for the ```TestEnum``` enum in my example comes back with 79 (!) properties that each need to be scanned. It seems to be going way off into JDK land and pulling things from not only ```Object```, but other reflection classes as well. I agree that we should include some additional exclusions on core JDK packages to catch this sort of thing.

**Comment by EricWittmann** [comment] 2019-10-03 12:21
Yeah I noticed the same thing when looking at #169 - does the `FilteredIndex` fix things?  If we exclude e.g. `java.*` for example.  Does that actually reduce what comes back from `TypeResolver.getAllFields`?

**Comment by MikeEdgar** [comment] 2019-10-04 01:29
FilteredIndex does reduce that. It turns out that most of the fields were coming from the parent ```Enum``` class that all `enum`s extend. 

One problem is that the index passed in from Quarkus is a ```CompositeIndex``` and the ```FilteredIndex``` is a few levels in from the top. To address that, I added a check to wrap the provided index before scanning starts to ensure the filtering works for the entire composite.

There is [some code in Quarkus](https://github.com/quarkusio/quarkus/blob/c972f05e0893ecd056e2af635324d3ac0fe04fe2/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L265) that is explicitly adding ```java.lang.Object``` to that unfiltered index. I'm not sure why that would have been necessary, but I do understand the previous two lines, which are in fact obsolete now that we handle those cases with the "standin" collections in ```OpenApiDataObjectScanner```.

**Comment by EricWittmann** [comment] 2019-10-04 14:02
So if we are getting a `CompositeIndex` with a `FilteredIndexView` inside it, then I guess we wrap everything in **another** `FilteredIndexView` and that results in us double-filtering?  Or perhaps the `OpenApiConfig` is different for the two...

**Comment by MikeEdgar** [comment] 2019-10-04 14:09
There will be two `FilteredIndexView`s in the index tree, but the filtering would be done at the top level - the index that is passed in, or wrapped, at the start of scanning. To avoid having the additional unneeded filters, Quarkus (and possibly others) should no longer create the filter itself.

**Comment by MikeEdgar** [comment] 2019-10-04 14:24
@kenfinnigan - I think we need a smallrye-open-api release with this fix for the Quarkus team to integrate/test before their release next week. This issue can stay open until confirmed fixed there.

**Comment by kenfinnigan** [comment] 2019-10-04 14:25
ok, will trigger a release

**Comment by kenfinnigan** [comment] 2019-10-04 14:39
Should be released, maybe a half hr to hit Central

**Comment by gastaldi** [comment] 2019-10-04 18:19
I can confirm that this fixes the issue

**Comment by gsmet** [comment] 2019-10-04 18:19
Thanks to everyone involved.

**Comment by MikeEdgar** [comment] 2019-10-04 18:30
Good to hear - thank you. Closing this issue.

**Closed by MikeEdgar** 2019-10-04 18:30 UTC
Labels: bug

**Comment by FroMage** [comment] 2019-10-08 10:37
This causes a regression in Quarkus: https://github.com/quarkusio/quarkus/issues/4329#issuecomment-539454820

**Comment by FroMage** [comment] 2019-10-08 10:39
To explain why we had `Object`, `Map` and `Collection` in the index: it was to avoid use of reflection in `TypeUtil.hasSuper` which you use in `OpenApiDataObjectScanner.initialType()` and `OpenApiDataObjectScanner.isSpecialType()` for pretty much every class, which causes reflection for every quarkus class, which has very nasty side-effects at this stage during our build.

**Comment by FroMage** [comment] 2019-10-08 10:51
@MikeEdgar @EricWittmann I can't think of any idea for working around this bug in Quarkus, and the regression is about as bad as the original OOM, so do you have any idea how to fix this in smallrye-openapi?

**Comment by FroMage** [comment] 2019-10-08 10:54
Apparently, if we are able to pass you a `ClassLoader` instead of you using `Class.forName` (which will always use the CL of smallrye-openapi), we can make this work. Or you can use the TCCL.

I can make a PR for either solution if you want.
