### ISSUE TITLE
[RFE]smallrye-openapi does not process javax.validation constraint @pattern and add it to the schemas it generated in openapi yaml file

### ISSUE THREAD

**Issue by asajigithub** [smallrye/smallrye-open-api#1121] opened 2022-04-12 01:30 UTC
For the code with following validation constraint  
~~~
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class Fruit {

    @NotNull
    @Size(min = 1, max = 4)
    @Pattern(regexp = "^[A-Za-z]+$")
    public String name;
~~~

From SwaggerUI-> OpenAPI, the document does not include the Pattern validation
~~~
components:
  schemas:
    Fruit:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 4
          minLength: 1
          type: string
          nullable: false
        description:
          type: string
~~~

**Comment by phillip-kruger** [comment] 2022-04-12 01:39
Duplicate of #1108 ??

**Closed** 2022-05-20 23:53 UTC
Labels: duplicate
