### ISSUE TITLE
Encoding problem between application.properties and generated spec

### ISSUE THREAD

**Issue by gquintana** [smallrye/smallrye-open-api#1547] opened 2023-08-21 15:38 UTC
I have a Quarkus application.properties (encoded in ISO-8859-1) containing:
```
quarkus.smallrye-openapi.info-description=API pour consulter les données de référence.
```

Smallrye Open API generates (encoded in UTF-8):
```
{
  "info" : {
    "description" : "API pour consulter les donn�es de r�f�rence",
  },
```

**Comment by MikeEdgar** [comment] 2023-08-22 12:07
@gquintana can you put together a small reproducer repository for this? We'll need to determine if this is an issue in Quarkus or smallrye-open-api and that would help speed things up.

**Comment by gquintana** [comment] 2023-08-23 07:44
> @gquintana can you put together a small reproducer repository for this? 

Here it is https://github.com/gquintana/test-quarkus-openapi

Actual output
```json
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "ACME API",
    "description" : "API pour les donn�es de r�f�rence ACME",
    "version" : "1.0.0-SNAPSHOT"
  },
```

![image](https://github.com/smallrye/smallrye-open-api/assets/755587/6fa2e0fe-5bdc-4d52-a6ea-c9e9f6efe07e)

**Comment by MikeEdgar** [comment] 2023-09-10 00:18
@gquintana is there a reason to use ISO-8859-1?

**Comment by gquintana** [comment] 2023-09-11 06:03
@MikeEdgar application.properties being a Java properties it's default encoding is ISO-8859-1 for historical reasons ( [Properties.load(InputStream) JavaDoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Properties.html#load(java.io.InputStream) ), IDEs encode it like this by default I guess. I ignore if it's still the norm today and how application.properties is being loaded by Quarkus.

**Comment by MikeEdgar** [comment] 2023-09-11 09:43
@radcortez has this issue come up before? It looks like smallrye-config reads properties as UTF-8 [1] but `Properties#load(InputStream)` assumes ISO-8859-1.

[1] https://github.com/smallrye/smallrye-config/blob/170642b18ee47c400e00b4b5afe2d0b8f7d2be85/common/src/main/java/io/smallrye/config/common/utils/ConfigSourceUtil.java#L77-L87

**Comment by radcortez** [comment] 2023-09-11 13:52
Hum, I don't remember any issue with it before, but I guess that is because it is not usual for configuration to be used for descriptions.

Please, open an issue in SmallRye Config and I can have a look into it. In the meanwhile, (and I can't believe I'm saying this!), I recommend using the yaml configuration, which should be ok.

**Comment by MikeEdgar** [comment] 2023-09-11 16:37
I've opened https://github.com/smallrye/smallrye-config/issues/995 to track this further. Since any change would be out of the scope of the smallrye-open-api project, I am also closing this.

cc: @gquintana

**Closed by MikeEdgar** 2023-09-11 16:37 UTC
